# Generated by Django 4.0 on 2021-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EndofDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Clearing_Member", models.CharField(max_length=100)),
                ("Account", models.CharField(max_length=40)),
                ("Margin_Class", models.CharField(max_length=20)),
                ("Margin", models.DecimalField(decimal_places=3, max_digits=13)),
                ("Report_Date", models.DateField()),
                ("Report_Time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Intraday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Clearing_Member", models.CharField(max_length=100)),
                ("Account", models.CharField(max_length=40)),
                ("Margin_Class", models.CharField(max_length=20)),
                ("Margin", models.DecimalField(decimal_places=3, max_digits=13)),
                ("Report_Date", models.DateField()),
            ],
        ),
    ]
