# Generated by Django 4.0 on 2021-12-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("margin_reports", "0003_remove_endofday_report_time_intraday_report_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marginclasssurveilance",
            name="Account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="margin_reports.account"
            ),
        ),
    ]
